export enum RouteNames {
  HOME = "/",
  MESSAGE_PAGE = "/messages",
  ADMIN = "/admin",
  PERSONAL_PAGE = "/user/=userID",
  PERSONAL_PHOTOS = "/user/=userID/=photos",
  NOTIFICATION = "/notification",
  BOOKMARKS = "/bookmarks",
  POST_PREVIEW = "/post/=postID",
  LOGIN = "/pages/authentication/login",
  REGISTER = "/register",
  LOGOUT = "/logout",
  TERM_AND_SERVICE = "/term-and-service",
  COOKIE_POLICY = "/cookie-policy",
  PRIVACY_POLICY = "/privacy-policy",
  EXPLORE = "/explore",
  ADVERTISES = "dashboards/advertises",
  USERS = "dashboards/users",
  POSTS = "dashboards/posts",
  ANALYTICS = "dashboards/analytics",
  ECOMMERCE = "dashboards/ecommerce",
  SALES = "dashboards/sales",
  PERSONAL = "dashboards/personal",
  PAYMENTS = "dashboards/payments",
  LIST_VIEW = "listview",
  CRM = "dashboards/crm",
  PAYMENT = "pages/payment"
}
