

export const MENUITEMS = [
  {
    menutitle: 'MAIN',
  },
      {
        icon: (<i className="side-menu__icon bx bx-home"></i>),
        type: 'sub',
        Name: '',
        active: false,
        selected: false,
        title: 'Dashboards',
        badge: '',
        badgetxt: '12',
        class: 'badge !bg-warning/10 !text-warning !py-[0.25rem] !px-[0.45rem] !text-[0.75em] ms-2',
        children: [
          { path: `${import.meta.env.BASE_URL}dashboards/crm`, type: 'link', active: false, selected: false, title: 'CRM' },
          { path: `${import.meta.env.BASE_URL}dashboards/ecommerce`, type: 'link', active: false, selected: false, title: 'Ecommerce' },
          { path: `${import.meta.env.BASE_URL}dashboards/crypto`, type: 'link', active: false, selected: false, title: 'Crypto' },
          { path: `${import.meta.env.BASE_URL}dashboards/jobs`, type: 'link', active: false, selected: false, title: 'Jobs' },
          { path: `${import.meta.env.BASE_URL}dashboards/nft`, type: 'link', active: false, selected: false, title: 'NFT' },
          { path: `${import.meta.env.BASE_URL}dashboards/sales`, type: 'link', active: false, selected: false, title: 'Sales' },
          { path: `${import.meta.env.BASE_URL}dashboards/analytics`, type: 'link', active: false, selected: false, title: 'Analytics' },
          { path: `${import.meta.env.BASE_URL}dashboards/projects`, type: 'link', active: false, selected: false, title: 'Projects' },
          { path: `${import.meta.env.BASE_URL}dashboards/hrm`, type: 'link', active: false, selected: false, title: 'HRM' },
          { path: `${import.meta.env.BASE_URL}dashboards/stocks`, type: 'link', active: false, selected: false, title: 'Stocks' },
          { path: `${import.meta.env.BASE_URL}dashboards/courses`, type: 'link', active: false, selected: false, title: 'Courses' },
          { path: `${import.meta.env.BASE_URL}dashboards/personal`, type: 'link', active: false, selected: false, title: 'Personal' }
        ]
      },
  {
    menutitle: "PAGES",
  },
      {
        icon: (<i className="bx bx-file-blank side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        title: "Pages",
        badge: '',
        badgetxt: 'New',
        class: ' text-secondary text-[0.75em] rounded-sm !py-[0.25rem] !px-[0.45rem] badge !bg-secondary/10 ms-2',
        children: [
          {
            path: `${import.meta.env.BASE_URL}pages/aboutus`,
            title: "About Us",
            type: "link",
            active: false,
            selected: false,
          },
          {
            title: "Blog",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}pages/blog/blog`,
                title: "Blog",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/blog/blogdetails`,
                title: "Blog Details",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/blog/createblog`,
                title: "Create Blog",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}pages/chat`,
            title: "Chat",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/contacts`,
            title: "Contacts",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/contactus`,
            title: "Contact Us",
            type: "link",
            active: false,
            selected: false,
          },
          {
            title: "Ecommerce",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/addproducts`,
                title: "Add Products",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/cart`,
                title: "Cart",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/checkout`,
                title: "Checkout",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/editproducts`,
                title: "Edit Products",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/orderdetails`,
                title: "Order Details",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/orders`,
                title: "Orders",
                type: "link",
                active: false,
                selected: false,
              }, {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/products`,
                title: "Products",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/productdetails`,
                title: "Product Details",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/productlist`,
                title: "Products List",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/ecommerce/wishlist`,
                title: "Wishlist",
                type: "link",
                active: false,
                selected: false,
              },

            ],
          },
          {
            title: "Email",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}pages/email/mailapp`,
                title: "Mail App",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/email/mailsettings`,
                title: "Mail Settings",
                type: "link",
                active: false,
                selected: false,
              },

            ],
          },
          {
            path: `${import.meta.env.BASE_URL}pages/empty`,
            title: "Empty",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/faqs`,
            title: "FAQ's",
            type: "link",
            active: false,
            selected: false,
          },
          {
            title: "File Manager",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}pages/filemanager/filemanager`,
                title: "File Manager",
                type: "link",
                active: false,
                selected: false,
              },
            ],
          },
          {
            title: "Invoice",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}pages/invoice/createinvoice`,
                title: "Create Invoice",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/invoice/invoicedetails`,
                title: "Invoice Details",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}pages/invoice/invoicelist`,
                title: "Invoice List",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}pages/landing`,
            title: "Landing",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/jobslanding`,
            title: "Jobs Landing",
            type: "link",
            class: 'text-secondary text-[0.75em] rounded-sm badge !py-[0.25rem] !px-[0.45rem] !bg-secondary/10 ms-2',
            badgetxt: 'New',
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/notifications`,
            title: "Notifications",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/pricing`,
            title: "Pricing",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/profile`,
            title: "Profile",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/reviews`,
            title: "Reviews",
            type: "link",
            active: false,
            selected: false,
          },

          {
            path: `${import.meta.env.BASE_URL}pages/team`,
            title: "Team",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/termsconditions`,
            title: "Terms & Conditions",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/timeline`,
            title: "Timeline",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}pages/todolist`,
            title: "To Do List",
            type: "link",
            active: false,
            selected: false,
          },

        ],
      },
      {
        icon: (<i className="bx bx-task side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        title: "Task",
        badge: '',
        badgetxt: 'New',
        class: 'text-secondary text-[0.75em] rounded-sm !py-[0.25rem] !px-[0.45rem] badge !bg-secondary/10 ms-2',
        children: [
          {
            path: `${import.meta.env.BASE_URL}task/kanbanboard`,
            title: "kanban Board",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}task/listview`,
            title: "List View",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}task/taskdetails`,
            title: "Task Details",
            type: "link",
            active: false,
            selected: false,
          },

        ],
      },
      {
        icon: (<i className="bx bx-fingerprint side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        title: "Authentication",
        badge: '',
        badgetxt: '',
        class: '',
        children: [
          {
            path: `${import.meta.env.BASE_URL}authentication/comingsoon`,
            title: "Coming Soon",
            type: "link",
            active: false,
            selected: false,
          },
          {
            title: "Create Password",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}authentication/createpassword/basic`,
                title: "Basic",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}authentication/createpassword/cover`,
                title: "Cover",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            title: "Lock Screen",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}authentication/lockbasic/lockbasic`,
                title: "Basic",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}authentication/lockcover/lockcover`,
                title: "Cover",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            title: "Reset Password",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}authentication/resetpassword/resetbasic`,
                title: "Basic",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}authentication/resetpassword/resetcover`,
                title: "Cover",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            title: "Sign Up",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}authentication/signup/signupbasic`,
                title: "Basic",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}authentication/signup/signupcover`,
                title: "Cover",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            title: "Sign In",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}authentication/signin/signinbasic`,
                title: "Basic",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}authentication/signin/signincover`,
                title: "Cover",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            title: "Two Step Verification",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}authentication/twostepverification/twostepbasic`,
                title: "Basic",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}authentication/twostepverification/twostepcover`,
                title: "Cover",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}authentication/undermaintenance`,
            title: "Under Maintenance",
            type: "link",
            active: false,
            selected: false,
          },

        ],
      },
      {
        icon: (<i className="bx bx-error side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        title: "Error",
        badge: '',
        badgetxt: '',
        class: '',
        children: [
          {
            path: `${import.meta.env.BASE_URL}error/401error`,
            title: "401- Error",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}error/404error`,
            title: "404- Error",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}error/500error`,
            title: "500- Error",
            type: "link",
            active: false,
            selected: false,
          },
        ],
      },
  {
    menutitle: 'GENERAL',
  },
      {
        icon: (<i className="bx bx-box side-menu__icon"></i>),
        type: 'sub',
        Name: '',
        active: false,
        selected: false,
        title: 'UI Elements',
        badge: '',
        badgetxt: '',
        class: '',
        children: [
          { path: `${import.meta.env.BASE_URL}uielements/alerts`, type: 'link', active: false, selected: false, title: 'Alerts' },
          { path: `${import.meta.env.BASE_URL}uielements/badge`, type: 'link', active: false, selected: false, title: 'Badge' },
          { path: `${import.meta.env.BASE_URL}uielements/breadcrumb`, type: 'link', active: false, selected: false, title: 'Breadcrumb' },
          { path: `${import.meta.env.BASE_URL}uielements/buttons`, type: 'link', active: false, selected: false, title: 'Buttons' },
          { path: `${import.meta.env.BASE_URL}uielements/buttongroup`, type: 'link', active: false, selected: false, title: 'Button Group' },
          { path: `${import.meta.env.BASE_URL}uielements/cards`, type: 'link', active: false, selected: false, title: 'Cards' },
          { path: `${import.meta.env.BASE_URL}uielements/dropdowns`, type: 'link', active: false, selected: false, title: 'Dropdowns' },
          { path: `${import.meta.env.BASE_URL}uielements/imagesfigures`, type: 'link', active: false, selected: false, title: 'Images & Figures' },
          { path: `${import.meta.env.BASE_URL}uielements/listgroup`, type: 'link', active: false, selected: false, title: 'List Group' },
          { path: `${import.meta.env.BASE_URL}uielements/navtabs`, type: 'link', active: false, selected: false, title: 'Navs & Tabs' },
          { path: `${import.meta.env.BASE_URL}uielements/objectfit`, type: 'link', active: false, selected: false, title: 'Object Fit' },
          { path: `${import.meta.env.BASE_URL}uielements/pagination`, type: 'link', active: false, selected: false, title: 'Pagination' },
          { path: `${import.meta.env.BASE_URL}uielements/popoovers`, type: 'link', active: false, selected: false, title: 'Popovers' },
          { path: `${import.meta.env.BASE_URL}uielements/progress`, type: 'link', active: false, selected: false, title: 'Progress' },
          { path: `${import.meta.env.BASE_URL}uielements/spinners`, type: 'link', active: false, selected: false, title: 'Spinners' },
          { path: `${import.meta.env.BASE_URL}uielements/toasts`, type: 'link', active: false, selected: false, title: 'Toasts' },
          { path: `${import.meta.env.BASE_URL}uielements/tooltips`, type: 'link', active: false, selected: false, title: 'Tooltips' },
          { path: `${import.meta.env.BASE_URL}uielements/indicators`, type: 'link', active: false, selected: false, title: 'Indicators' }
        ]
      },
      {
        icon: (<i className="bx bx-medal side-menu__icon"></i>),
        type: 'sub',
        Name: '',
        active: false,
        selected: false,
        title: 'Utilities',
        badge: '',
        badgetxt: '',
        class: '',
        children: [
          { path: `${import.meta.env.BASE_URL}utilities/avatars`, type: 'link', active: false, selected: false, title: 'Avatars' },
          { path: `${import.meta.env.BASE_URL}utilities/borders`, type: 'link', active: false, selected: false, title: 'Borders' },
          { path: `${import.meta.env.BASE_URL}utilities/colors`, type: 'link', active: false, selected: false, title: 'Colors' },
          { path: `${import.meta.env.BASE_URL}utilities/grids`, type: 'link', active: false, selected: false, title: 'Grids' },
          { path: `${import.meta.env.BASE_URL}utilities/flex`, type: 'link', active: false, selected: false, title: 'Flex' },
          { path: `${import.meta.env.BASE_URL}utilities/columns`, type: 'link', active: false, selected: false, title: 'Columns' }
        ]
      },
      {
        icon: (<i className="bx bx-file side-menu__icon"></i>),
        type: 'sub',
        Name: '',
        active: false,
        selected: false,
        title: 'Forms',
        badge: '',
        badgetxt: '',
        class: '',
        children: [
          {
            title: "Form Elements",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/inputs`,
                title: "Inputs",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/checksradios`,
                title: "Checks & Radios",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/inputgroup`,
                title: "Input Group",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/formselect`,
                title: "Form Select",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/rangeslider`,
                title: "Range Slider",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/fileuploads`,
                title: "File Uploads",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/datetimepicker`,
                title: "Date,Time Picker",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}forms/formelements/colorpickers`,
                title: "Color Pickers",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          { path: `${import.meta.env.BASE_URL}forms/formlayouts`, type: 'link', active: false, selected: false, title: 'Form Layouts' },
          {
            title: "Form Editors",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}forms/formeditor/quilleditor`,
                title: "Quill Editor",
                type: "link",
                active: false,
                selected: false,
              },
            ],
          },
          { path: `${import.meta.env.BASE_URL}forms/validation`, type: 'link', active: false, selected: false, title: 'Validation' },
          { path: `${import.meta.env.BASE_URL}forms/select2`, type: 'link', active: false, selected: false, title: 'Select2' }
        ]
      },
      {
        icon: (<i className="bx bx-party side-menu__icon"></i>),
        type: 'sub',
        Name: '',
        active: false,
        selected: false,
        title: 'Advanced Ui',
        badge: '',
        badgetxt: '',
        class: '',
        children: [
          { path: `${import.meta.env.BASE_URL}advancedui/accordionscollapse`, type: 'link', active: false, selected: false, title: 'Accordions & Collapse' },
          { path: `${import.meta.env.BASE_URL}advancedui/draggablecards`, type: 'link', active: false, selected: false, title: 'Draggable Cards' },
          { path: `${import.meta.env.BASE_URL}advancedui/modalscloses`, type: 'link', active: false, selected: false, title: 'Modals & Closes' },
          { path: `${import.meta.env.BASE_URL}advancedui/navbar`, type: 'link', active: false, selected: false, title: 'Navbar' },
          { path: `${import.meta.env.BASE_URL}advancedui/offcanvas`, type: 'link', active: false, selected: false, title: 'Offcanvas' },
          { path: `${import.meta.env.BASE_URL}advancedui/ratings`, type: 'link', active: false, selected: false, title: 'Rating' },
          { path: `${import.meta.env.BASE_URL}advancedui/scrollspy`, type: 'link', active: false, selected: false, title: 'Scrollspy' },
          { path: `${import.meta.env.BASE_URL}advancedui/swiperjs`, type: 'link', active: false, selected: false, title: 'Swiper JS' },

        ]
      },
      {
        path: `${import.meta.env.BASE_URL}widgets`,
        icon: (<i className="bx bx-gift side-menu__icon"></i>),
        title: "Widgets",
        type: "link",
        badge: '',
        badgetxt: 'Hot',
        class: 'text-danger text-[0.75em] rounded-sm badge !py-[0.25rem] !px-[0.45rem] !bg-danger/10 ms-2',
        selected: false,
        active: false,
      },

  {
    menutitle: "WEB APPS",
  },
      {
        icon: (<i className=" bx bx-grid-alt side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        badge: '',
        badgetxt: 'New',
        class: 'text-secondary text-[0.75em] rounded-sm !py-[0.25rem] !px-[0.45rem] badge !bg-secondary/10 ms-2',
        title: "Apps",
        children: [
          {
            path: `${import.meta.env.BASE_URL}apps/fullcalendar`,
            type: "link",
            active: false,
            selected: false,
            title: "Full Calendar",
          },
          {
            path: `${import.meta.env.BASE_URL}apps/gallery`,
            type: "link",
            active: false,
            selected: false,
            title: "Gallery",
          },
          {
            title: "Projects",
            type: "sub",
            selected: false,
            active: false,
            badge: '',
            badgetxt: '',
            class: '',
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/projects/projectslist`,
                title: "Projects List",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/projects/projectoverview`,
                title: "Project Overview",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/projects/createproject`,
                title: "Create Project",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            title: "Jobs",
            type: "sub",
            selected: false,
            active: false,
            badge: '',
            badgetxt: '',
            class: '',
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/jobdetails`,
                title: "Job Details",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/searchcompany`,
                title: "Search Company",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/searchjobs`,
                title: "Search Jobs",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/jobpost`,
                title: "Job Post",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/jobslist`,
                title: "Jobs List",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/searchcandidate`,
                title: "Search Candidate",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/jobs/candidatedetails`,
                title: "Candidate Details",
                type: "link",
                active: false,
                selected: false,
              },

            ],
          },
          {
            title: "NFT",
            type: "sub",
            selected: false,
            active: false,
            badge: '',
            badgetxt: '',
            class: '',
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/nft/marketplace`,
                title: "Market Place",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/nft/nftdetails`,
                title: "NFT Details",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/nft/createnft`,
                title: "Create NFT",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/nft/walletintegration`,
                title: "wallet Integration",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/nft/liveauction`,
                title: "Live Auction",
                type: "link",
                active: false,
                selected: false,
              },

            ],
          },
          {
            title: "CRM",
            type: "sub",
            selected: false,
            badge: '',
            badgetxt: '',
            class: '',
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/crm/crmcontacts`,
                title: "Contacts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crm/companies`,
                title: "Companies",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crm/deals`,
                title: "Deals",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crm/leads`,
                title: "Leads",
                type: "link",
                active: false,
                selected: false,
              },

            ],
          },
          {
            title: "Crypto",
            type: "sub",
            selected: false,
            active: false,
            badge: '',
            badgetxt: '',
            class: '',
            children: [
              {
                path: `${import.meta.env.BASE_URL}apps/crypto/transactions`,
                title: "Transactions",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crypto/currencyexchange`,
                title: "Currency Exchange",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crypto/buysell`,
                title: "Buy & Sell",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crypto/marketcap`,
                title: "Marketcap",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apps/crypto/wallet`,
                title: "Wallet",
                type: "link",
                active: false,
                selected: false,
              },

            ],
          },

        ],
      },
      {
        title: "Nested Menu",
        icon: (
          <i className="bx bx-layer side-menu__icon"></i>
        ),
        type: "sub",
        selected: false,
        active: false,
        children: [
          {
            path: '#',
            title: "Nested-1",
            type: "empty",
            active: false,
            selected: false,
          },
          {
            title: "Nested-2",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: '#',
                title: "Nested-2.1",
                type: "empty",
                active: false,
                selected: false,
              },
              {
                path: '#',
                title: "Nested-2.2",
                type: "empty",
                active: false,
                selected: false,
              },

            ],
          },
        ],
      },
  {
    menutitle: "TABLES & CHARTS",
  },
      {
        icon: (<i className="bx bx-table side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        badge: '',
        badgetxt: '3',
        class: 'text-success text-[0.75em] badge !py-[0.25rem] !px-[0.45rem] rounded-sm bg-success/10 ms-2',
        title: "Tables",
        children: [
          {
            path: `${import.meta.env.BASE_URL}tables/tables`,
            title: "Tables",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}tables/gridjstables`,
            title: "Grid JS Tables",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}tables/datatables`,
            title: "Data Tables",
            type: "link",
            active: false,
            selected: false,
          },
        ],
      },
      {
        icon: (<i className="bx bx-bar-chart-square side-menu__icon"></i>),
        type: "sub",
        NameL: '',
        active: false,
        selected: false,
        badge: '',
        badgetxt: '',
        class: '',
        title: "Charts",
        children: [
          {
            title: "Apex Charts",
            type: "sub",
            selected: false,
            active: false,
            children: [
              {
                path: `${import.meta.env.BASE_URL}apexcharts/linecharts`,
                title: "Line Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/areacharts`,
                title: "Area Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/columncharts`,
                title: "Column Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/barcharts`,
                title: "Bar Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/mixedcharts`,
                title: "Mixed Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/rangeareacharts`,
                title: "Range Area Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/timelinecharts`,
                title: "Timeline Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/candlestickcharts`,
                title: "CandleStick Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/boxplotcharts`,
                title: "Boxplot Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/bubblecharts`,
                title: "Bubble Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/scattercharts`,
                title: "Scatter Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/heatmapcharts`,
                title: "Heatmap Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/treemapcharts`,
                title: "Treemap Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/piecharts`,
                title: "Pie Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/radialbarcharts`,
                title: "Radialbar Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/radarcharts`,
                title: "Radar Charts",
                type: "link",
                active: false,
                selected: false,
              },
              {
                path: `${import.meta.env.BASE_URL}apexcharts/polarareacharts`,
                title: "Polararea Charts",
                type: "link",
                active: false,
                selected: false,
              }
            ],
          },
          {
            path: `${import.meta.env.BASE_URL}charts/chartjscharts`,
            title: "Chartjs Charts",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}charts/echartscharts`,
            title: "Echart Charts",
            type: "link",
            active: false,
            selected: false,
          },
        ],
      },


  {
    menutitle: "MAPS & ICONS",
  },
      {
        icon: (<i className="bx bx-map side-menu__icon"></i>),
        type: "sub",
        Name: '',
        active: false,
        selected: false,
        badge: '',
        badgetxt: '',
        class: '',
        title: "Maps",
        children: [
          {
            path: `${import.meta.env.BASE_URL}maps/leafletmaps`,
            title: "Leaflet Maps",
            type: "link",
            active: false,
            selected: false,
          },
          {
            path: `${import.meta.env.BASE_URL}maps/vectormaps`,
            title: "Vector Maps",
            type: "link",
            active: false,
            selected: false,
          },
        ],
      },
      {
        path: `${import.meta.env.BASE_URL}icons`,
        icon: (<i className="bx bx-store-alt side-menu__icon"></i>),
        type: "link",
        selected: false,
        active: false,
        title: "Icons",
      },

];
